import pandas as pd


def richer_table():
    '''
    uses the aggregated table generated by vacc_death_agre_table.py
    generates a richer table with population density and
    GDP per capita
    save into a csv file as final_aggregated_table
    '''
    df = pd.read_csv('datasets/aggregated_table_v_d_rate_by_state.csv')
    statenames = pd.read_csv('datasets/StateNames.csv')

    # concentrate population density dataset
    density_df = pd.read_csv('datasets/apportionment.csv')
    density_df = density_df[(density_df['Year'] == 2020) &
                            (density_df['Geography Type'] == 'State')]
    columns = ['Name', 'Resident Population Density']
    density_df = density_df[columns]
    density_df = density_df.merge(statenames,
                                  left_on='Name',
                                  right_on='State',
                                  how='left')
    density_df = density_df[['State', 'Resident Population Density', 'Code']]
    den = 'Resident Population Density'
    density_df[den] = density_df[den].str.replace(r'[^\w\s]+', '')
    density_df[den] = pd.to_numeric(density_df[den])

    # concentrate gdp dataset
    gdp_df = pd.read_csv('datasets/bea-gdp-by-state.csv')
    columns = ['Area', '2017']
    gdp_df = gdp_df[columns]

    # merge density & gdp
    den_gdp_df = gdp_df.merge(density_df,
                              left_on='Area',
                              right_on='State',
                              how='inner')
    den_gdp_df = den_gdp_df.rename(columns={'2017': 'GDP per capita'})
    columns = ['GDP per capita', 'Resident Population Density', 'Code']
    den_gdp_df = den_gdp_df[columns]

    # combine everything
    df = df.merge(den_gdp_df, left_on='Code', right_on='Code', how='left')
    df = df[['Code', 'COVID_Death_Rate', 'Vaccine_Rate',
             'GDP per capita', 'Resident Population Density']]

    df.to_csv('final_aggregated_table.csv')


def main():
    richer_table()


if __name__ == '__main__':
    main()
